# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new Internal Track Build to Google Play"
  lane :internal do
    increment_version_code(
      gradle_file_path: "app/build.gradle",
    )
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store(
      track: "internal",
      skip_upload_apk: true,
      release_status: "draft"
    )
  end

  lane :build_release_apk do
    gradle(task: "clean assembleRelease")
  end

  lane :build_release_bundle do
    gradle(task: "clean bundle", build_type: "Release")
  end
end
